
apiVersion: v1
kind: Service
metadata:
  name: vue-template
  namespace: prophet
  labels:
    k8s-app: vue-template
spec:
  ports:
  - port: 80             #Service的端口号
    name: web
    targetPort: 80           #容器暴露的端口号
    nodePort: 30008            #node的真实端口号
  selector:
    k8s-app: vue-template             #service选择了标签为k8s-app: dgs-admin的pod
  externalTrafficPolicy: Local
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-template
  namespace: prophet
  labels:
    k8s-app: vue-template
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vue-template
  template:
    metadata:
      labels:
        k8s-app: vue-template
    spec:
      nodeSelector:
        master: "yes"
      #hostNetwork: true
      #hostPID: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: vue-template
        image: harbor.pcitech.com/prophet/vue-template:1.0.0
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: vue-template-config
          mountPath: /app/config.js
          subPath: config.js
        - name: vue-template-logs
          mountPath: /app/logs
        - name: localtime
          readOnly: true
          mountPath: "/etc/localtime"
        - name: localtime
          readOnly: true
          mountPath: "/etc/timezone"
      - name: fluentd
        image: harbor.pcitech.com/base/fluentd-elasticsearch:v2.2.0
        imagePullPolicy: Always
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - name: vue-template-logs
          mountPath: /var/log/vue-template
        - name: config-volume
          mountPath: /etc/fluent/config.d
        - name: localtime
          readOnly: true
          mountPath: "/etc/localtime"
        - name: localtime
          readOnly: true
          mountPath: "/etc/timezone"
      volumes:
        - name: vue-template-config
          configMap:
            name: vue-template-config
            items:
              - key: config
                path: config.js
        - name: config-volume
          configMap:
            name: fluentd-configmap-vue-template
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: vue-template-logs
          emptyDir: {}
